/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotesredo;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {
    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();

        Quote.generateLocalQuote();
        //step 1 create url and an HTTP url connection
        URL starUrl = new URL(" http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
        HttpURLConnection starConnections = (HttpURLConnection) starUrl.openConnection();

        //Step 2: set our headers, check response code, use try/catch to handle bad urls + close connection

        try {
            starConnections.setRequestMethod("GET");
            int starStatus = starConnections.getResponseCode();
            System.out.println(starStatus);

            //Step 3: if code is usable get data as a stream
            if (starStatus == 200){
                // step 4: get data as a stream
                InputStreamReader starStreamReader = new InputStreamReader(starConnections.getInputStream());

                //Step 5: use BuffedReader to read the input(can also use starReade.read()
                try(BufferedReader starBufferedReader = new BufferedReader(starStreamReader)){
                    String line = starBufferedReader.readLine();
                    //System.out.println(line);


                    //Step 6 part 1: create class(es) to convert formatted JSON Java Objects (come back here when you are done )
                    //Step 6 par 2: use GSON to create your Java objects
                    Gson gson2 = new Gson();
                    Quote apiQuote = gson.fromJson(line, Quote.class);


                    //Write JSON to file

                    File quoteFileOut = new File("./app/src/main/resources/recentquotes.json");
                    try (FileWriter quoteFileWriter = new FileWriter(quoteFileOut,true)){
                        gson2.toJson(apiQuote, quoteFileWriter);
                        System.out.println("TEST");
                    } catch(IOException ioe){
                        System.out.println("Caught an IOException with stack trace: ");
                        ioe.printStackTrace();
                    }

                }
            }

        }catch (MalformedURLException mue){
            System.out.println("bad URL");
            mue.printStackTrace();
        } catch (IOException ioe){
            System.out.println("problem with API");
            ioe.printStackTrace();
        } finally {
            starConnections.disconnect();
        }





    }
}


