/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotesredo;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;

class AppTest {

    //grab gson to read json files
    //read all our quotes from a json file
    //place all the quotes into an array
    //randomly select one quote and print its author/text to the screen

    Gson gson = new Gson();
    FileReader myFile = new FileReader("./app/src/main/resources/recentquotes.json");

    AppTest() throws FileNotFoundException {
    }
}
